# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AuxotWorker < Formula
  desc "GPU inference worker for the Auxot platform"
  homepage "https://github.com/auxothq/auxot-server"
  version "0.1.40"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.40/auxot_0.1.40_darwin_amd64.tar.gz"
      sha256 "4426e1355e5e5655742a36efceb6b391c79c7d307577930a1ad8ba796af30749"

      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.40/auxot_0.1.40_darwin_arm64.tar.gz"
      sha256 "cf5ddbf10500625f829e70094343397eaa76bae59871db662d569f44861ca808"

      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.40/auxot_0.1.40_linux_amd64.tar.gz"
      sha256 "b224b36b0681693416f672ea3cbc40393e46ffae335e5b418dbd441aeff73426"
      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.40/auxot_0.1.40_linux_arm64.tar.gz"
      sha256 "31d8e13bcef139e6c979ea17fc19f3174b901f24c58d7d0093cf2264e5dccbca"
      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
  end

  def caveats
    <<~EOS
      To connect immediately (foreground):
        auxot-worker --gpu-key <key>

      To install as a persistent daemon (starts on boot):
        auxot-worker install --name default --gpu-key <key>
        sudo auxot-worker install --name default --gpu-key <key> --always-on

      Manage installed workers:
        auxot-worker list
        auxot-worker uninstall <name>
    EOS
  end

  test do
    output = shell_output("#{bin}/auxot-worker version")
    assert_match "auxot-worker", output
  end
end
