# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AuxotWorker < Formula
  desc "GPU inference worker for the Auxot platform"
  homepage "https://github.com/auxothq/auxot-server"
  version "0.1.35"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.35/auxot_0.1.35_darwin_amd64.tar.gz"
      sha256 "7123d837abb1fda79edd33d8ccf001f1a0fdc92bec60a74e86353f976bea04e2"

      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.35/auxot_0.1.35_darwin_arm64.tar.gz"
      sha256 "cb6e5e10ee414713c4e72625a766e6ad47502a28dc926e48576fdbe6876d92a2"

      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.35/auxot_0.1.35_linux_amd64.tar.gz"
      sha256 "c8fefd46a7c7c35e34958acf78ddfbb18d8fdb9e35eb01ca0b5d17cbd06c9e3f"
      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/auxothq/auxot-server/releases/download/v0.1.35/auxot_0.1.35_linux_arm64.tar.gz"
      sha256 "c3256d910de70d05d073bf38387f9dd3b214e1363e53b541fb234ea5cb722a78"
      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
  end

  def caveats
    <<~EOS
      To connect immediately (foreground):
        auxot-worker --gpu-key <key>

      To install as a persistent daemon (starts on boot):
        auxot-worker install --name default --gpu-key <key>
        sudo auxot-worker install --name default --gpu-key <key> --always-on

      Manage installed workers:
        auxot-worker list
        auxot-worker uninstall <name>
    EOS
  end

  test do
    output = shell_output("#{bin}/auxot-worker version")
    assert_match "auxot-worker", output
  end
end
