# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AuxotWorker < Formula
  desc "GPU inference worker for the Auxot platform"
  homepage "https://github.com/auxothq/auxot"
  version "0.3.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/auxothq/auxot/releases/download/v0.3.12/auxot_0.3.12_darwin_amd64.tar.gz"
      sha256 "fd9878a3654b157b4df343d8b6d9207a55cca7ef0b9e705ed019eabcf4118db6"

      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/auxothq/auxot/releases/download/v0.3.12/auxot_0.3.12_darwin_arm64.tar.gz"
      sha256 "25fb676bdd145801927a5131d927769d706acb2c9f4aadf9225e6b2ce0a0e0b0"

      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/auxothq/auxot/releases/download/v0.3.12/auxot_0.3.12_linux_amd64.tar.gz"
      sha256 "72e0f602d01f4a9a123233d252d9d7f2f5a18585db4a548ca0654b6cbaeed091"
      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/auxothq/auxot/releases/download/v0.3.12/auxot_0.3.12_linux_arm64.tar.gz"
      sha256 "d94ac3378ee0f11638c31ae4693f9d6e713eb1caf231d1b3a8e73a44a73d699e"
      define_method(:install) do
        bin.install "auxot-worker"
      end
    end
  end

  def caveats
    <<~EOS
      To connect immediately (foreground):
        auxot-worker --gpu-key <key>

      To install as a persistent daemon (starts on boot):
        auxot-worker install --name default --gpu-key <key>
        sudo auxot-worker install --name default --gpu-key <key> --always-on

      Manage installed workers:
        auxot-worker list
        auxot-worker uninstall <name>
    EOS
  end

  test do
    output = shell_output("#{bin}/auxot-worker version")
    assert_match "auxot-worker", output
  end
end
